import type { Article, Look } from "./types";

export const looks: Look[] = [
  {
    id: "lk1",
    slug: "sunday-trans-ekulu",
    name: "Sunday in Trans Ekulu",
    gender: "women",
    occasion: "Church",
    description: "Covered, cream, and finished. The tie-waist midi, a nude heel you can stand in, a soft bag and pearls.",
    image: "/images/church-portrait.jpg",
    productIds: ["ss020", "ss046", "ss055", "ss058"],
    colours: ["Cream", "Nude", "Gold"],
  },
  {
    id: "lk2",
    slug: "owambe-guest",
    name: "Owambe Guest",
    gender: "women",
    occasion: "Wedding",
    description: "Wine aso-oke, a court heel, a beaded clutch and hoops. Gele is your own business.",
    image: "/images/edit-wedding.jpg",
    productIds: ["ss040", "ss049", "ss056", "ss057"],
    colours: ["Wine", "Gold"],
  },
  {
    id: "lk3",
    slug: "gra-date",
    name: "GRA Date Night",
    gender: "women",
    occasion: "Date",
    description: "Black satin, a mule, a chain bag. Dinner in GRA without a performance.",
    image: "/images/edit-date.jpg",
    productIds: ["ss031", "ss004", "ss047", "ss054"],
    colours: ["Black"],
  },
  {
    id: "lk4",
    slug: "desk-to-dinner",
    name: "Desk to Dinner",
    gender: "women",
    occasion: "Office",
    description: "The Enugu pencil, nude heels, a burgundy mini bag. Leave the office and keep walking.",
    image: "/images/edit-office.jpg",
    productIds: ["ss015", "ss046", "ss052", "ss058"],
    colours: ["Black", "Burgundy"],
  },
  {
    id: "lk5",
    slug: "wine-studio",
    name: "Wine Studio",
    gender: "women",
    occasion: "Dinner",
    description: "The cowl midi, a burgundy court, a structured bag and hoops. One colour, three textures.",
    image: "/images/hero-portrait.jpg",
    productIds: ["ss001", "ss049", "ss052", "ss057"],
    colours: ["Burgundy", "Wine"],
  },
  {
    id: "lk6",
    slug: "new-haven-friday",
    name: "New Haven Friday",
    gender: "men",
    occasion: "Casual",
    description: "Navy polo, stone chinos, a white court sneaker and a belt. The Friday that still looks like you tried.",
    image: "/images/hero-man.jpg",
    productIds: ["ss066", "ss079", "ss093", "ss096"],
    colours: ["Navy", "Stone", "White"],
  },
  {
    id: "lk7",
    slug: "groomman",
    name: "Groomsman, GRA",
    gender: "men",
    occasion: "Wedding",
    description: "Ivory native, black loafer, a gold watch and a belt. The family photo will be kind.",
    image: "/images/hero-man.jpg",
    productIds: ["ss088", "ss113", "ss098", "ss096"],
    colours: ["Ivory", "Black", "Gold"],
  },
  {
    id: "lk8",
    slug: "weekend-uniform",
    name: "Weekend Uniform",
    gender: "men",
    occasion: "Casual",
    description: "Heavyweight tee, black jeans, a runner and slim sunglasses. Enugu or Yaba, same answer.",
    image: "/images/edit-street.jpg",
    productIds: ["ss061", "ss076", "ss094", "ss101"],
    colours: ["Black", "Charcoal"],
  },
  {
    id: "lk9",
    slug: "interview-ready",
    name: "Interview Ready",
    gender: "men",
    occasion: "Interview",
    description: "Sky oxford, navy trouser, black loafer, steel watch. Nothing that needs adjusting in the waiting room.",
    image: "/images/edit-office.jpg",
    productIds: ["ss070", "ss082", "ss113", "ss099"],
    colours: ["Sky", "Navy", "Black"],
  },
  {
    id: "lk10",
    slug: "yellow-day",
    name: "Yellow Day Out",
    gender: "women",
    occasion: "Casual",
    description: "The butter t-shirt dress, a woven flat, a tote and tortoise sunnies. Under a sensible budget.",
    image: "/images/edit-street.jpg",
    productIds: ["ss008", "ss048", "ss053", "ss100"],
    colours: ["Butter", "Tan"],
  },
  {
    id: "lk11",
    slug: "introduction-day",
    name: "Introduction Day",
    gender: "women",
    occasion: "Wedding",
    description: "Red isiagu-inspired set, a court heel and a clutch. For the guest who is almost family.",
    image: "/images/edit-wedding.jpg",
    productIds: ["ss044", "ss049", "ss056", "ss058"],
    colours: ["Red", "Gold"],
  },
  {
    id: "lk12",
    slug: "agbada-morning",
    name: "Agbada Morning",
    gender: "men",
    occasion: "Wedding",
    description: "Cream agbada, a brown oxford and a gold watch. The full traditional, edited.",
    image: "/images/edit-native.jpg",
    productIds: ["ss090", "ss114", "ss098"],
    colours: ["Cream", "Gold"],
  },
];

export const articles: Article[] = [
  {
    slug: "what-to-wear-to-a-nigerian-wedding",
    title: "What to Wear to a Nigerian Wedding",
    excerpt: "Aso-ebi is a brief. Everything else is a decision. Here is how to dress for the traditional, the church and the reception without buying three wardrobes.",
    image: "/images/edit-wedding.jpg",
    date: "12 September 2026",
    read: "6 min",
    category: "Occasion",
    body: [
      "A Nigerian wedding is rarely one event. There is the introduction, the traditional, the church, and a reception that can run until the generator starts to sound personal. Dressing for it is not about owning the most fabric. It is about knowing which room you are walking into.",
      "If you are in aso-ebi, wear the aso-ebi. Do not fight it with a competing print. Finish it with one good shoe, a clutch you can actually close, and jewellery that survives sweat and photographs. Gele is optional. A well-tied scarf or a clean hair moment is better than a gele that gives up at 4pm.",
      "If you are a guest without a colour brief, wine, emerald, royal and cream still read as occasion in Enugu and Lagos. Avoid looking like the couple. White is for the bride unless the card says otherwise. Black can work at a night reception and can look like a funeral at a morning traditional. Read the room, and the invitation.",
      "Comfort is not the opposite of dressing up. You will stand for photos, sit for speeches, and dance to at least one song you did not plan to dance to. A block heel beats a blade heel. A wrapper you can walk in beats a wrapper you have to hold. STYLESORT listings say when gele is not included, and when a piece is ready-to-wear rather than made-to-measure. Believe the listing.",
      "Budget, honestly: a guest look under ₦50,000 is realistic if the dress or native set is the spend and the shoes are a pair you will wear to church next month. Over ₦80,000, you are in agbada and aso-oke territory, and you should be, if the day is yours or your sibling's.",
      "Shop the wedding guest edit, then build the rest in Complete Looks. If you are unsure, send the invitation to STYLESORT on WhatsApp. We would rather answer than watch you arrive in the wrong white.",
    ],
  },
  {
    slug: "five-essential-wardrobe-pieces-for-men",
    title: "5 Essential Wardrobe Pieces for Men",
    excerpt: "A heavyweight tee, an oxford, dark jeans, a chino, and a shoe that can meet a senator. The Nigerian calendar is not only office or only owambe.",
    image: "/images/hero-man.jpg",
    date: "28 August 2026",
    read: "5 min",
    category: "Men",
    body: [
      "Most men's wardrobe advice assumes a life of offices and weekends. Nigerian men also have introductions, thanksgivings, and a Friday that starts in New Haven and ends at a family house. Five pieces cover more of that than a cupboard of logos.",
      "One: a heavyweight tee in charcoal, black or white. Not a souvenir tee. Weight means it hangs, washes, and does not twist. It is the base of the weekend uniform.",
      "Two: an oxford or a clean dress shirt in white or sky. Interviews, church when the dress code is quiet, and the dinner that was supposed to be casual and was not.",
      "Three: dark jeans with a rise that works under a polo and does not fight a native shirt if you wear one open. Four: stone or navy chinos. They make a polo look finished, which is the entire trick of Friday.",
      "Five: one shoe that can meet both a trouser and a senator. A black loafer or a clean court sneaker. If you attend traditionals, the sixth piece is not optional: a well-cut senator or a kaftan in a colour you will wear more than once. Black, ivory, deep green.",
      "You do not need ten pairs of sneakers. You need one pair that is clean this week. STYLESORT men's edit is built around that idea, with sizes through XXXL, because a wardrobe essential that stops at L is not essential.",
    ],
  },
  {
    slug: "how-to-style-a-two-piece-set",
    title: "How to Style a Two-Piece Set",
    excerpt: "Wear it as intended. Then split it. A co-ord is three outfits if you refuse to be precious about it.",
    image: "/images/ugc-1.jpg",
    date: "4 September 2026",
    read: "4 min",
    category: "Styling",
    body: [
      "A two-piece set is the fastest way to look dressed in Nigeria, where the day often contains two dress codes and one okada. The mistake is treating the set as a single object you cannot touch.",
      "First way: wear it as sold. Ankara co-ord to a party. Linen vest and trouser to travel. Satin shirt and short to a date. Add one shoe and one small bag. Stop. The set is already the outfit.",
      "Second way: split it. The vest over jeans. The trouser with a white tee. The ankara blouse with a plain black skirt you already own. This is how a ₦22,000 set becomes three weeks of clothes.",
      "Third way: change the shoe and you change the room. A woven flat makes the linen set a Saturday. A court heel makes the same vest a Tuesday meeting. A mule makes the satin set a night. Complete the Look on each product page prices the add-ons so you can see the real total before you fall in love.",
      "Fit note: sets are cut to match each other, not necessarily to match a shirt from another seller. If you are between sizes, size for the trouser. A blouse can be tucked. A trouser that gapes cannot.",
    ],
  },
  {
    slug: "best-church-outfits",
    title: "Best Church Outfits",
    excerpt: "Covered shoulders are not a punishment. The best Sunday clothes are the ones you forget you are wearing by the second reading.",
    image: "/images/church-portrait.jpg",
    date: "20 September 2026",
    read: "5 min",
    category: "Occasion",
    body: [
      "Enugu churches can run long. Lagos churches can run longer. The outfit that wins is not the loudest. It is the one that still looks like a decision when you stand up for the last hymn.",
      "For women, a midi with covered shoulders solves most dress codes without looking like you borrowed your auntie's jacket. Cream, black, forest and soft terracotta photograph well in daylight compounds. A tie waist gives shape without a tight cut. Grace Edit and Adaora both cut for this, and the size guide goes to XXXL.",
      "Shoes: a nude block heel or a woven flat. If you will stand in the car park afterwards, believe the flat. Bags: structured enough that your Bible, phone and offering envelope are not a performance.",
      "For men, a white polo is not underdressing if it is opaque and pressed. A sky oxford is safer if your parish is formal. Native is welcome in many churches on thanksgiving Sunday. Ivory senator, black trouser, clean shoe. You do not need an agbada for a regular Sunday unless the programme says so.",
      "Children: cotton, not itchy tulle, unless it is a birthday that happens to fall on a Sunday. Nneka Little exists because somebody's child cried through praise and worship in a scratchy dress. We took that personally.",
      "Shop the church edit, filter by your size, and check delivery before Saturday night. Same-day in Enugu is real if you order before 1pm. It is not a personality trait. It is a cutoff.",
    ],
  },
  {
    slug: "date-night-outfit-ideas",
    title: "Date-Night Outfit Ideas",
    excerpt: "GRA dinner, a lounge, or jollof at a place with good light. Three outfits, and what they actually cost.",
    image: "/images/edit-date.jpg",
    date: "2 October 2026",
    read: "4 min",
    category: "Occasion",
    body: [
      "Date night in Nigeria is rarely a single template. It might be a restaurant in GRA with warm light, a lounge where you will stand, or somewhere the generator is part of the ambience. Dress for the chair, or the lack of one.",
      "The black satin cami with a slip or a tailored trouser is the shortest path. It looks like you meant it. Add a mule and a small bag. Leave the extra necklace at home. One shine is enough.",
      "If you do not want a dress, the wine satin set does the same job with more movement. If you want to spend less, the Ifunanya slip and a pair of hoops you already own will clear ₦15,000 and still look like a plan.",
      "For men: burgundy polo and stone chinos if the place is relaxed. Cuban collar if it is not. A senator is a date outfit if the person you are meeting understands that you might come from a family event. Many of us do. Do not apologise for it. Change the shoe if the senator was for the afternoon.",
      "Budget a ceiling before you open the app. Build My Outfit will do it with you: gender, occasion, colour, the number you actually have. The point of STYLESORT is not to spend more. It is to stop guessing.",
    ],
  },
  {
    slug: "outfit-under-20k",
    title: "How to Build an Outfit Under ₦20K",
    excerpt: "The maths, not the moodboard. Where to spend, where to save, and a full look that stays inside the number.",
    image: "/images/edit-street.jpg",
    date: "1 October 2026",
    read: "5 min",
    category: "Budget",
    body: [
      "Under ₦20,000 is not a compromise aisle. It is where most weekly dressing in Nigeria actually happens. The trick is to spend on the piece people see first, and save on the piece that finishes it.",
      "A butter t-shirt dress at ₦11,200 plus a woven flat at ₦8,500 is already ₦19,700, and it is a complete outfit. If you need a bag, drop to the gold hoops at ₦4,800 and a dress under ₦15,000, and carry the tote you own.",
      "For men: charcoal tee ₦6,500, and you still have ₦13,500. That does not buy the court sneaker. It does buy stone chinos if you already have shoes, or a polo if you already have trousers. Under ₦20,000 for men is a top and a bottom, or a shoe and a tee. Not all three, unless one of them is a belt.",
      "Do not buy a cheap shoe to complete an expensive dress. Buy the shoe you will wear to church, and let the dress be the ₦12,000 one. Repeat wear is the real discount.",
      "Use Shop Under ₦20K, then sort by highest rated. Ratings on STYLESORT come from people who had the piece delivered to Awka, PH and Enugu, not from a stock photo. If a thrift piece is one-of-one, the listing says so. Measure against the size guide. There is no second one.",
      "If you want the whole thing chosen for you, open Build My Outfit and set the budget to ₦20,000. We will not sneak a ₦45,000 gown into the result and call it inspiration.",
    ],
  },
];

export const COUPONS = [
  { code: "WELCOME10", label: "10% off your first order" },
  { code: "ENUGU2K", label: "₦2,000 off Enugu delivery" },
  { code: "SORT5", label: "₦5,000 off orders over ₦40,000" },
  { code: "INSIDER15", label: "15% for Insider members" },
  { code: "WEEKEND", label: "10% off, Friday to Sunday" },
];
