import type { Seller } from "./types";

export const sellers: Seller[] = [
  {
    id: "adaora",
    slug: "adaora-atelier",
    name: "Adaora Atelier",
    type: "Fashion designer",
    city: "Enugu",
    area: "Independence Layout",
    state: "Enugu",
    verified: true,
    rating: 4.9,
    reviews: 312,
    responseRate: 98,
    responseTime: "within 1 hour",
    deliveryScore: 96,
    since: 2021,
    bio: "Adaora Atelier cuts easy dresses and sets for women who want to look considered without trying too hard. Studio pickup is available on Independence Layout.",
    specialties: ["Dresses", "Two-Piece Sets", "Office Wear"],
    image: "/images/hero-portrait.jpg",
  },
  {
    id: "nkem",
    slug: "nkem-studio",
    name: "Nkem Studio",
    type: "Boutique",
    city: "Lagos",
    area: "Lekki Phase 1",
    state: "Lagos",
    verified: true,
    rating: 4.7,
    reviews: 540,
    responseRate: 94,
    responseTime: "within 3 hours",
    deliveryScore: 91,
    since: 2019,
    bio: "Contemporary womenswear edited in Lagos and shipped nationwide. Nkem Studio is known for party pieces that photograph well and survive the after-party.",
    specialties: ["Party Dresses", "Tops", "Sets"],
    image: "/images/edit-date.jpg",
  },
  {
    id: "chuka",
    slug: "house-of-chuka",
    name: "House of Chuka",
    type: "Native-wear designer",
    city: "Enugu",
    area: "GRA",
    state: "Enugu",
    verified: true,
    rating: 4.9,
    reviews: 208,
    responseRate: 97,
    responseTime: "within 2 hours",
    deliveryScore: 95,
    since: 2016,
    bio: "Agbada, senator and isiagu cut for modern Nigerian men. House of Chuka has dressed groomsmen from Enugu to Abuja for ten years.",
    specialties: ["Agbada", "Native Wear", "Kaftans"],
    image: "/images/edit-native.jpg",
  },
  {
    id: "zuri",
    slug: "zuri-thrift",
    name: "Zuri Thrift",
    type: "Thrift seller",
    city: "Abuja",
    area: "Wuse 2",
    state: "FCT",
    verified: true,
    rating: 4.6,
    reviews: 890,
    responseRate: 92,
    responseTime: "within 4 hours",
    deliveryScore: 88,
    since: 2022,
    bio: "Carefully selected thrift and archive pieces, steamed, measured and photographed properly. If it is listed, it is the only one.",
    specialties: ["Jeans", "Tops", "Vintage"],
    image: "/images/edit-street.jpg",
  },
  {
    id: "kelechi",
    slug: "kelechi-footwear",
    name: "Kelechi Footwear",
    type: "Shoe seller",
    city: "Aba",
    area: "Ariaria",
    state: "Abia",
    verified: true,
    rating: 4.5,
    reviews: 670,
    responseRate: 90,
    responseTime: "within 5 hours",
    deliveryScore: 86,
    since: 2018,
    bio: "Aba-made shoes with honest leather and shapes that work from office to owambe. Kelechi ships from Aba with a fitting note in every box.",
    specialties: ["Shoes", "Sandals", "Sneakers"],
    image: "/images/edit-office.jpg",
  },
  {
    id: "amaka",
    slug: "amaka-bags",
    name: "Amaka Bags",
    type: "Bag seller",
    city: "Lagos",
    area: "Surulere",
    state: "Lagos",
    verified: true,
    rating: 4.8,
    reviews: 410,
    responseRate: 96,
    responseTime: "within 2 hours",
    deliveryScore: 93,
    since: 2020,
    bio: "Structured bags and soft totes made for Nigerian commutes — church, office, and the market run after.",
    specialties: ["Bags", "Clutches"],
    image: "/images/edit-office.jpg",
  },
  {
    id: "obi",
    slug: "obi-and-co",
    name: "Obi & Co.",
    type: "Boutique",
    city: "Enugu",
    area: "New Haven",
    state: "Enugu",
    verified: true,
    rating: 4.7,
    reviews: 255,
    responseRate: 95,
    responseTime: "within 2 hours",
    deliveryScore: 94,
    since: 2020,
    bio: "Men's weekend and office staples. Obi & Co. keeps the cuts clean and the prices honest for Enugu.",
    specialties: ["Shirts", "Chinos", "Polos"],
    image: "/images/hero-man.jpg",
  },
  {
    id: "ifunanya",
    slug: "ifunanya-native",
    name: "Ifunanya Native",
    type: "Native-wear designer",
    city: "Onitsha",
    area: "GRA Onitsha",
    state: "Anambra",
    verified: true,
    rating: 4.8,
    reviews: 188,
    responseRate: 93,
    responseTime: "within 3 hours",
    deliveryScore: 90,
    since: 2017,
    bio: "Ankara, aso-oke and adire for women who want native that does not feel like a costume. Ready pieces, and short made-to-measure on WhatsApp.",
    specialties: ["Native Wear", "Ankara", "Aso-oke"],
    image: "/images/edit-wedding.jpg",
  },
  {
    id: "lumi",
    slug: "lumi-accessories",
    name: "Lumi Accessories",
    type: "Accessory seller",
    city: "Port Harcourt",
    area: "GRA Phase 2",
    state: "Rivers",
    verified: false,
    rating: 4.4,
    reviews: 96,
    responseRate: 88,
    responseTime: "within a day",
    deliveryScore: 84,
    since: 2023,
    bio: "Earrings, scarves, belts and the small things that finish an outfit. Lumi is newer on STYLESORT and growing fast.",
    specialties: ["Accessories", "Jewellery"],
    image: "/images/edit-date.jpg",
  },
  {
    id: "tobi",
    slug: "tobi-street",
    name: "Tobi Street",
    type: "Streetwear label",
    city: "Lagos",
    area: "Yaba",
    state: "Lagos",
    verified: true,
    rating: 4.6,
    reviews: 340,
    responseRate: 91,
    responseTime: "within 4 hours",
    deliveryScore: 89,
    since: 2021,
    bio: "Heavyweight tees, easy trousers and sneaker energy. Tobi Street is what students order when they want Lagos without the flight.",
    specialties: ["T-shirts", "Streetwear", "Sneakers"],
    image: "/images/edit-street.jpg",
  },
  {
    id: "grace",
    slug: "grace-edit",
    name: "Grace Edit",
    type: "Boutique",
    city: "Enugu",
    area: "Trans Ekulu",
    state: "Enugu",
    verified: true,
    rating: 4.8,
    reviews: 276,
    responseRate: 99,
    responseTime: "within 1 hour",
    deliveryScore: 97,
    since: 2018,
    bio: "Church, thanksgiving and Sunday-best dressing without the stiffness. Grace Edit understands covered shoulders and still wants you to look like yourself.",
    specialties: ["Church Outfits", "Modest Dresses"],
    image: "/images/church-portrait.jpg",
  },
  {
    id: "marina",
    slug: "marina-edit",
    name: "Marina Edit",
    type: "Boutique",
    city: "Lagos",
    area: "Victoria Island",
    state: "Lagos",
    verified: true,
    rating: 4.7,
    reviews: 198,
    responseRate: 94,
    responseTime: "within 3 hours",
    deliveryScore: 92,
    since: 2019,
    bio: "Office dresses, shirts and tailored trousers for people who have an 8am stand-up and a 7pm dinner.",
    specialties: ["Office Wear", "Shirts", "Trousers"],
    image: "/images/edit-office.jpg",
  },
  {
    id: "nneka",
    slug: "nneka-little",
    name: "Nneka Little",
    type: "Kids boutique",
    city: "Enugu",
    area: "Independence Layout",
    state: "Enugu",
    verified: true,
    rating: 4.9,
    reviews: 120,
    responseRate: 97,
    responseTime: "within 2 hours",
    deliveryScore: 95,
    since: 2022,
    bio: "Small sizes, proper fabric, nothing itchy. Nneka Little dresses children for church, parties and the Tuesday school run.",
    specialties: ["Kids"],
    image: "/images/ugc-1.jpg",
  },
];

export function getSeller(id: string) {
  return sellers.find((s) => s.id === id || s.slug === id);
}
